### ISSUE TITLE
loadBanner 不调用

### ISSUE THREAD

**Issue by LayneCui** [xiaohaibin/XBanner#111]
banner 作为 RecyclerView 的一个 item 使用，初始化完成，setBannerData后，不会走loadBanner回调，所以 banner 不能显示出来，求大神指导

**Comment by xiaohaibin** [comment]
不可能不走回调，除非你没设置回调方法




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年06月28日 17:56，LayneCui 写道：

banner 作为 RecyclerView 的一个 item 使用，初始化完成，setBannerData后，不会走loadBanner回调，所以 banner 不能显示出来，求大神指导

**Comment by LayneCui** [comment]
按照 demo 写的呢：


LinearLayout.LayoutParams layoutParams = new 
                    LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, 
                    ScreenUtil.getScreenWidth(getActivity()) / 2);

            viewHolderBanner.mBanner.setLayoutParams(layoutParams);

            initBanner(viewHolderBanner.mBanner);

            //刷新数据之后，需要重新设置是否支持自动轮播
            viewHolderBanner.mBanner.setAutoPlayAble(banner.getBannerList().size() > 1);
            viewHolderBanner.mBanner.setIsClipChildrenMode(true);
            viewHolderBanner.mBanner.setBannerData(R.layout.banner_item_padding, 
                    compareBannerList(banner.getBannerList()));






/**
         * 初始化XBanner
         */
        private void initBanner(XBanner banner) {
            //设置广告图片点击事件
            banner.setOnItemClickListener(new XBanner.OnItemClickListener() {
                @Override
                public void onItemClick(XBanner banner, Object model, View view, int position) {
                    Toast.makeText(getActivity(), "点击了第" + (position + 1) + "图片", 
                            Toast.LENGTH_SHORT).show();
                }
            });
            //加载广告图片
            banner.loadImage(new XBanner.XBannerAdapter() {
                @Override
                public void loadBanner(XBanner banner, Object model, View view, int position) {
                    List<HomeV5BannerItem> datas = ((List<HomeV5BannerItem>)model);
                    SimpleDraweeView draweeView = (SimpleDraweeView) view;
                    draweeView.setImageURI(Uri.parse(datas.get(position).getTarget_img()));

                }
            });
        }

**Comment by xiaohaibin** [comment]
断点看下，数据设置进去没




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年06月28日 18:02，LayneCui 写道：

按照 demo 写的呢：

LinearLayout.LayoutParams layoutParams = new
LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,
ScreenUtil.getScreenWidth(getActivity()) / 2);

        viewHolderBanner.mBanner.setLayoutParams(layoutParams);



        initBanner(viewHolderBanner.mBanner);



        //刷新数据之后，需要重新设置是否支持自动轮播

        viewHolderBanner.mBanner.setAutoPlayAble(banner.getBannerList().size() > 1);

        viewHolderBanner.mBanner.setIsClipChildrenMode(true);

        viewHolderBanner.mBanner.setBannerData(R.layout.banner_item_padding, 

                compareBannerList(banner.getBannerList()));



/**
* 初始化XBanner
*/
private void initBanner(XBanner banner) {
//设置广告图片点击事件
banner.setOnItemClickListener(new XBanner.OnItemClickListener() {
@override
public void onItemClick(XBanner banner, Object model, View view, int position) {
Toast.makeText(getActivity(), "点击了第" + (position + 1) + "图片",
Toast.LENGTH_SHORT).show();
}
});
//加载广告图片
banner.loadImage(new XBanner.XBannerAdapter() {
@override
public void loadBanner(XBanner banner, Object model, View view, int position) {
List datas = ((List)model);
SimpleDraweeView draweeView = (SimpleDraweeView) view;
draweeView.setImageURI(Uri.parse(datas.get(position).getTarget_img()));

            }

        });

    }

**Comment by LayneCui** [comment]
现在可以了，感谢大佬

**Comment by AliceChjy** [comment]
你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by xiaohaibin** [comment]
已经更新了代码，下载更新下吧




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月22日 14:20，chenjy 写道：

你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by AliceChjy** [comment]
我直接加依赖试了&nbsp; 还是不行&nbsp; 之前是加2现在是加1&nbsp; 点2的时候item的position为3 也同样滑动到第三




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午3:49
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





 已经更新了代码，下载更新下吧
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月22日 14:20，chenjy 写道：
 
 你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by AliceChjy** [comment]
我直接加依赖试了&nbsp; 还是不行&nbsp; 之前是加2现在是加1&nbsp; 点2的时候item的position为3 也同样滑动到第三
不对，我刚看了下我项目里加依赖的XBanner源码，还是之前的，不是你修改以后的，像你这种修复了的我这边之前加的依赖不会同步更新吗，还是你这边版本要设置&nbsp; 我用的1.7.3的




------------------ 原始邮件 ------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午3:49
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





 已经更新了代码，下载更新下吧
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月22日 14:20，chenjy 写道：
 
 你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by xiaohaibin** [comment]
你不是下载的源码嘛




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月27日 15:27，chenjy 写道：

我直接加依赖试了&nbsp; 还是不行&nbsp; 之前是加2现在是加1&nbsp; 点2的时候item的position为3 也同样滑动到第三
不对，我刚看了下我项目里加依赖的XBanner源码，还是之前的，不是你修改以后的，像你这种修复了的我这边之前加的依赖不会同步更新吗，还是你这边版本要设置&nbsp; 我用的1.7.3的




------------------ 原始邮件 ------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午3:49
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





已经更新了代码，下载更新下吧




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月22日 14:20，chenjy 写道：

你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by AliceChjy** [comment]
之前只是源码试下能不能实现我要的效果，可以用了我当然用的依赖啦





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午3:31
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





 你不是下载的源码嘛
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 15:27，chenjy 写道：
 
 我直接加依赖试了&amp;nbsp; 还是不行&amp;nbsp; 之前是加2现在是加1&amp;nbsp; 点2的时候item的position为3 也同样滑动到第三
 不对，我刚看了下我项目里加依赖的XBanner源码，还是之前的，不是你修改以后的，像你这种修复了的我这边之前加的依赖不会同步更新吗，还是你这边版本要设置&amp;nbsp; 我用的1.7.3的
 
 
 
 
 ------------------ 原始邮件 ------------------
 发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年4月22日(星期三) 下午3:49
 收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 已经更新了代码，下载更新下吧
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月22日 14:20，chenjy 写道：
 
 你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by xiaohaibin** [comment]
更新到1.7.4看下




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月27日 15:39，chenjy 写道：

之前只是源码试下能不能实现我要的效果，可以用了我当然用的依赖啦





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午3:31
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





你不是下载的源码嘛




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月27日 15:27，chenjy 写道：

我直接加依赖试了&amp;nbsp; 还是不行&amp;nbsp; 之前是加2现在是加1&amp;nbsp; 点2的时候item的position为3 也同样滑动到第三
不对，我刚看了下我项目里加依赖的XBanner源码，还是之前的，不是你修改以后的，像你这种修复了的我这边之前加的依赖不会同步更新吗，还是你这边版本要设置&amp;nbsp; 我用的1.7.3的




------------------ 原始邮件 ------------------
发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年4月22日(星期三) 下午3:49
收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





已经更新了代码，下载更新下吧




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月22日 14:20，chenjy 写道：

你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by AliceChjy** [comment]
还是有问题 &nbsp; 现在点击和滑动对上 了，但只限点右边的正常 &nbsp; 点击左边的有问题 &nbsp; 例如当前是8&nbsp; 点击左边的7吐司还是8&nbsp; 选择页也是8




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 晚上6:37
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





 更新到1.7.4看下
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 15:39，chenjy 写道：
 
 之前只是源码试下能不能实现我要的效果，可以用了我当然用的依赖啦
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年4月27日(星期一) 下午3:31
 收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 你不是下载的源码嘛
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 15:27，chenjy 写道：
 
 我直接加依赖试了&amp;amp;nbsp; 还是不行&amp;amp;nbsp; 之前是加2现在是加1&amp;amp;nbsp; 点2的时候item的position为3 也同样滑动到第三
 不对，我刚看了下我项目里加依赖的XBanner源码，还是之前的，不是你修改以后的，像你这种修复了的我这边之前加的依赖不会同步更新吗，还是你这边版本要设置&amp;amp;nbsp; 我用的1.7.3的
 
 
 
 
 ------------------ 原始邮件 ------------------
 发件人:&amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;gt;;
 发送时间:&amp;amp;nbsp;2020年4月22日(星期三) 下午3:49
 收件人:&amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;gt;;
 抄送:&amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;
 主题:&amp;amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 已经更新了代码，下载更新下吧
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月22日 14:20，chenjy 写道：
 
 你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by xiaohaibin** [comment]
我测试是正常的，录个视频看下你的操作吧




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月27日 19:30，chenjy 写道：

还是有问题 &nbsp; 现在点击和滑动对上 了，但只限点右边的正常 &nbsp; 点击左边的有问题 &nbsp; 例如当前是8&nbsp; 点击左边的7吐司还是8&nbsp; 选择页也是8




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 晚上6:37
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





更新到1.7.4看下




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月27日 15:39，chenjy 写道：

之前只是源码试下能不能实现我要的效果，可以用了我当然用的依赖啦





------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年4月27日(星期一) 下午3:31
收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





你不是下载的源码嘛




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月27日 15:27，chenjy 写道：

我直接加依赖试了&amp;amp;nbsp; 还是不行&amp;amp;nbsp; 之前是加2现在是加1&amp;amp;nbsp; 点2的时候item的position为3 也同样滑动到第三
不对，我刚看了下我项目里加依赖的XBanner源码，还是之前的，不是你修改以后的，像你这种修复了的我这边之前加的依赖不会同步更新吗，还是你这边版本要设置&amp;amp;nbsp; 我用的1.7.3的




------------------ 原始邮件 ------------------
发件人:&amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;gt;;
发送时间:&amp;amp;nbsp;2020年4月22日(星期三) 下午3:49
收件人:&amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;gt;;
抄送:&amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;
主题:&amp;amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





已经更新了代码，下载更新下吧




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月22日 14:20，chenjy 写道：

你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by AliceChjy** [comment]
不好意思，前段时间忙其他的去了。我这边重新下你的demo看了下代码是没问题的，但还有三个地方需要修复①点击左侧你这边限定了必须自动轮播，非自动下就没反应，我这边就设定为非自动，所以点击左边没反应
②我直接依赖用1.7.4你后面新改得并没有，所以导致我用依赖的时候无效果
③上面两个问题修复后我要是使用X版本的话是对应什么版本号

感谢亲一直回复我邮件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月28日(星期二) 上午9:30
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





 我测试是正常的，录个视频看下你的操作吧
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 19:30，chenjy 写道：
 
 还是有问题 &amp;nbsp; 现在点击和滑动对上 了，但只限点右边的正常 &amp;nbsp; 点击左边的有问题 &amp;nbsp; 例如当前是8&amp;nbsp; 点击左边的7吐司还是8&amp;nbsp; 选择页也是8
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年4月27日(星期一) 晚上6:37
 收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 更新到1.7.4看下
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 15:39，chenjy 写道：
 
 之前只是源码试下能不能实现我要的效果，可以用了我当然用的依赖啦
 
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
 发件人:&amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;gt;;
 发送时间:&amp;amp;nbsp;2020年4月27日(星期一) 下午3:31
 收件人:&amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;gt;;
 抄送:&amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;
 主题:&amp;amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 你不是下载的源码嘛
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 15:27，chenjy 写道：
 
 我直接加依赖试了&amp;amp;amp;nbsp; 还是不行&amp;amp;amp;nbsp; 之前是加2现在是加1&amp;amp;amp;nbsp; 点2的时候item的position为3 也同样滑动到第三
 不对，我刚看了下我项目里加依赖的XBanner源码，还是之前的，不是你修改以后的，像你这种修复了的我这边之前加的依赖不会同步更新吗，还是你这边版本要设置&amp;amp;amp;nbsp; 我用的1.7.3的
 
 
 
 
 ------------------ 原始邮件 ------------------
 发件人:&amp;amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;amp;gt;;
 发送时间:&amp;amp;amp;nbsp;2020年4月22日(星期三) 下午3:49
 收件人:&amp;amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;amp;gt;;
 抄送:&amp;amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;
 主题:&amp;amp;amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 已经更新了代码，下载更新下吧
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月22日 14:20，chenjy 写道：
 
 你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui

**Comment by AliceChjy** [comment]
还有一个问题④在设置非自动循环但isHandLoop为true的时候 ，点击最后一张再点击第一张的时候走下图判断，但图片没有伸出来，效果看附件视频（视频女孩为第一张，左边建筑是最后一张）



------------------ 原始邮件 ------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月28日(星期二) 上午9:30
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)





 我测试是正常的，录个视频看下你的操作吧
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 19:30，chenjy 写道：
 
 还是有问题 &amp;nbsp; 现在点击和滑动对上 了，但只限点右边的正常 &amp;nbsp; 点击左边的有问题 &amp;nbsp; 例如当前是8&amp;nbsp; 点击左边的7吐司还是8&amp;nbsp; 选择页也是8
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年4月27日(星期一) 晚上6:37
 收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 更新到1.7.4看下
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 15:39，chenjy 写道：
 
 之前只是源码试下能不能实现我要的效果，可以用了我当然用的依赖啦
 
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
 发件人:&amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;gt;;
 发送时间:&amp;amp;nbsp;2020年4月27日(星期一) 下午3:31
 收件人:&amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;gt;;
 抄送:&amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;
 主题:&amp;amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 你不是下载的源码嘛
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月27日 15:27，chenjy 写道：
 
 我直接加依赖试了&amp;amp;amp;nbsp; 还是不行&amp;amp;amp;nbsp; 之前是加2现在是加1&amp;amp;amp;nbsp; 点2的时候item的position为3 也同样滑动到第三
 不对，我刚看了下我项目里加依赖的XBanner源码，还是之前的，不是你修改以后的，像你这种修复了的我这边之前加的依赖不会同步更新吗，还是你这边版本要设置&amp;amp;amp;nbsp; 我用的1.7.3的
 
 
 
 
 ------------------ 原始邮件 ------------------
 发件人:&amp;amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;amp;gt;;
 发送时间:&amp;amp;amp;nbsp;2020年4月22日(星期三) 下午3:49
 收件人:&amp;amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;amp;gt;;
 抄送:&amp;amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;
 主题:&amp;amp;amp;nbsp;Re: [xiaohaibin/XBanner] loadBanner 不调用 (#111)
 
 
 
 
 
 已经更新了代码，下载更新下吧
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月22日 14:20，chenjy 写道：
 
 你是设置数据哪里出问题了，不会进loadBanner回调，我这边也是进不去，setBannerData后断点说mAdapter为空 @LayneCui
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Record_2020-05-29-15-08-55.mp4 (12.12M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=61666635f22e5fc60389389644375316005152500652035c1f515301561a555800074b0d555256140a50005754065458000050046229616b570509470668530900564b05571a53001f575318520f4c0c07480b4556375c&t=exs_ftn_download&code=2ff5b7a9
