### ISSUE TITLE
一屏显示多个时banner的item点击事件对应的position不对

### ISSUE THREAD

**Issue by AliceChjy** [xiaohaibin/XBanner#163]
点击当前选中的左侧或者右侧position却滑动到position+2，点击事件得到的position也为实际position+2
相当于点击事件和滑动事件不对应（实际点击了position2却滑动到4，position值得到是4，只单纯滑动事件就正常）
我需要点击或滑动的时候获取不同数据
点击事件拿到的position我可以自己减去2，但滑动到position+2就不知道怎么弄

**Comment by xiaohaibin** [comment]
版本多少




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 16:55，chenjy 写道：

点击当前选中的左侧或者右侧position却滑动到position+2，点击事件得到的position也为实际position+2
相当于点击事件和滑动事件不对应（实际点击了position2却滑动到4，position值得到是4，只单纯滑动事件就正常）
我需要点击或滑动的时候获取不同数据
点击事件拿到的position我可以自己减去2，但滑动到position+2就不知道怎么弄

**Comment by AliceChjy** [comment]
你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高  二是添加了缓存页面为5  mViewPager.setOffscreenPageLimit(5);
不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出

**Comment by xiaohaibin** [comment]
代码版本号，其实不用下载源码的




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 16:59，chenjy 写道：

你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出

**Comment by AliceChjy** [comment]
你好 &nbsp; 可否帮我看下
我知道直接放项目依赖就可以，我就是想先再源码里改成我想要的再添加依赖再改对应的地方就可以
我这边把我改了的源码发你看下，你原本的一屏展示3个，左右各露出一点，点击事件和滑动事件都正常，但我这边是需要一屏能展示5个（好像到时加依赖时没找到怎么设置这个方法mViewPager.setOffscreenPageLimit(5);），所以修改了我前面说得两个地方和布局里clipChildrenLeftRightMargin属性，可能就出问题了，是不是和你很多地方比较一屏是否大于3个有关系 麻烦帮我看下   谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午5:03
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





 代码版本号，其实不用下载源码的
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 16:59，chenjy 写道：
 
 你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
 我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
 不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

XBanner-master.rar (24.57M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7331383133dd14ce05de66924434501f0c07085557005007195301085b195602065515090605531d0c0359055605505557090e50622662687650565f07464f5d55424c54101a1051463105&t=exs_ftn_download&code=4181b4b0

**Comment by xiaohaibin** [comment]
是拉的最新的版本源码么




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 17:21，chenjy 写道：

你好 &nbsp; 可否帮我看下
我知道直接放项目依赖就可以，我就是想先再源码里改成我想要的再添加依赖再改对应的地方就可以
我这边把我改了的源码发你看下，你原本的一屏展示3个，左右各露出一点，点击事件和滑动事件都正常，但我这边是需要一屏能展示5个（好像到时加依赖时没找到怎么设置这个方法mViewPager.setOffscreenPageLimit(5);），所以修改了我前面说得两个地方和布局里clipChildrenLeftRightMargin属性，可能就出问题了，是不是和你很多地方比较一屏是否大于3个有关系 麻烦帮我看下 谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午5:03
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





代码版本号，其实不用下载源码的




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 16:59，chenjy 写道：

你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

XBanner-master.rar (24.57M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7331383133dd14ce05de66924434501f0c07085557005007195301085b195602065515090605531d0c0359055605505557090e50622662687650565f07464f5d55424c54101a1051463105&t=exs_ftn_download&code=4181b4b0

**Comment by AliceChjy** [comment]
对的，昨天下的。应该就是和我设置clipChildrenLeftRightMargin这个的原因


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午5:50
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





 是拉的最新的版本源码么
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 17:21，chenjy 写道：
 
 你好 &amp;nbsp; 可否帮我看下
 我知道直接放项目依赖就可以，我就是想先再源码里改成我想要的再添加依赖再改对应的地方就可以
 我这边把我改了的源码发你看下，你原本的一屏展示3个，左右各露出一点，点击事件和滑动事件都正常，但我这边是需要一屏能展示5个（好像到时加依赖时没找到怎么设置这个方法mViewPager.setOffscreenPageLimit(5);），所以修改了我前面说得两个地方和布局里clipChildrenLeftRightMargin属性，可能就出问题了，是不是和你很多地方比较一屏是否大于3个有关系 麻烦帮我看下 谢谢
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年4月21日(星期二) 下午5:03
 收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)
 
 
 
 
 
 代码版本号，其实不用下载源码的
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 16:59，chenjy 写道：
 
 你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
 我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
 不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 
 从QQ邮箱发来的超大附件
 
 XBanner-master.rar (24.57M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7331383133dd14ce05de66924434501f0c07085557005007195301085b195602065515090605531d0c0359055605505557090e50622662687650565f07464f5d55424c54101a1051463105&amp;t=exs_ftn_download&amp;code=4181b4b0

**Comment by xiaohaibin** [comment]
你跑下demo试下




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 17:51，chenjy 写道：

对的，昨天下的。应该就是和我设置clipChildrenLeftRightMargin这个的原因


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午5:50
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





是拉的最新的版本源码么




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 17:21，chenjy 写道：

你好 &amp;nbsp; 可否帮我看下
我知道直接放项目依赖就可以，我就是想先再源码里改成我想要的再添加依赖再改对应的地方就可以
我这边把我改了的源码发你看下，你原本的一屏展示3个，左右各露出一点，点击事件和滑动事件都正常，但我这边是需要一屏能展示5个（好像到时加依赖时没找到怎么设置这个方法mViewPager.setOffscreenPageLimit(5);），所以修改了我前面说得两个地方和布局里clipChildrenLeftRightMargin属性，可能就出问题了，是不是和你很多地方比较一屏是否大于3个有关系 麻烦帮我看下 谢谢





------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年4月21日(星期二) 下午5:03
收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





代码版本号，其实不用下载源码的




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 16:59，chenjy 写道：

你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

XBanner-master.rar (24.57M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7331383133dd14ce05de66924434501f0c07085557005007195301085b195602065515090605531d0c0359055605505557090e50622662687650565f07464f5d55424c54101a1051463105&amp;t=exs_ftn_download&amp;code=4181b4b0

**Comment by AliceChjy** [comment]
demo是没问题的&nbsp; 我改了这个clipChildrenLeftRightMargin和这个mViewPager.setOffscreenPageLimit(5)就有问题了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上6:12
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





 你跑下demo试下
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 17:51，chenjy 写道：
 
 对的，昨天下的。应该就是和我设置clipChildrenLeftRightMargin这个的原因
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年4月21日(星期二) 下午5:50
 收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)
 
 
 
 
 
 是拉的最新的版本源码么
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 17:21，chenjy 写道：
 
 你好 &amp;amp;nbsp; 可否帮我看下
 我知道直接放项目依赖就可以，我就是想先再源码里改成我想要的再添加依赖再改对应的地方就可以
 我这边把我改了的源码发你看下，你原本的一屏展示3个，左右各露出一点，点击事件和滑动事件都正常，但我这边是需要一屏能展示5个（好像到时加依赖时没找到怎么设置这个方法mViewPager.setOffscreenPageLimit(5);），所以修改了我前面说得两个地方和布局里clipChildrenLeftRightMargin属性，可能就出问题了，是不是和你很多地方比较一屏是否大于3个有关系 麻烦帮我看下 谢谢
 
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
 发件人:&amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;gt;;
 发送时间:&amp;amp;nbsp;2020年4月21日(星期二) 下午5:03
 收件人:&amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;gt;;
 抄送:&amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;
 主题:&amp;amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)
 
 
 
 
 
 代码版本号，其实不用下载源码的
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 16:59，chenjy 写道：
 
 你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
 我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
 不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 
 从QQ邮箱发来的超大附件
 
 XBanner-master.rar (24.57M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7331383133dd14ce05de66924434501f0c07085557005007195301085b195602065515090605531d0c0359055605505557090e50622662687650565f07464f5d55424c54101a1051463105&amp;amp;t=exs_ftn_download&amp;amp;code=4181b4b0

**Comment by xiaohaibin** [comment]
margin你改成多少了




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 18:22，chenjy 写道：

demo是没问题的&nbsp; 我改了这个clipChildrenLeftRightMargin和这个mViewPager.setOffscreenPageLimit(5)就有问题了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上6:12
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





你跑下demo试下




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 17:51，chenjy 写道：

对的，昨天下的。应该就是和我设置clipChildrenLeftRightMargin这个的原因


------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年4月21日(星期二) 下午5:50
收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





是拉的最新的版本源码么




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 17:21，chenjy 写道：

你好 &amp;amp;nbsp; 可否帮我看下
我知道直接放项目依赖就可以，我就是想先再源码里改成我想要的再添加依赖再改对应的地方就可以
我这边把我改了的源码发你看下，你原本的一屏展示3个，左右各露出一点，点击事件和滑动事件都正常，但我这边是需要一屏能展示5个（好像到时加依赖时没找到怎么设置这个方法mViewPager.setOffscreenPageLimit(5);），所以修改了我前面说得两个地方和布局里clipChildrenLeftRightMargin属性，可能就出问题了，是不是和你很多地方比较一屏是否大于3个有关系 麻烦帮我看下 谢谢





------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
发件人:&amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;gt;;
发送时间:&amp;amp;nbsp;2020年4月21日(星期二) 下午5:03
收件人:&amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;gt;;
抄送:&amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;
主题:&amp;amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





代码版本号，其实不用下载源码的




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 16:59，chenjy 写道：

你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

XBanner-master.rar (24.57M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7331383133dd14ce05de66924434501f0c07085557005007195301085b195602065515090605531d0c0359055605505557090e50622662687650565f07464f5d55424c54101a1051463105&amp;amp;t=exs_ftn_download&amp;amp;code=4181b4b0

**Comment by AliceChjy** [comment]
130


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上6:25
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





 margin你改成多少了
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 18:22，chenjy 写道：
 
 demo是没问题的&amp;nbsp; 我改了这个clipChildrenLeftRightMargin和这个mViewPager.setOffscreenPageLimit(5)就有问题了
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年4月21日(星期二) 晚上6:12
 收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)
 
 
 
 
 
 你跑下demo试下
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 17:51，chenjy 写道：
 
 对的，昨天下的。应该就是和我设置clipChildrenLeftRightMargin这个的原因
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
 发件人:&amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;gt;;
 发送时间:&amp;amp;nbsp;2020年4月21日(星期二) 下午5:50
 收件人:&amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;gt;;
 抄送:&amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;
 主题:&amp;amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)
 
 
 
 
 
 是拉的最新的版本源码么
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 17:21，chenjy 写道：
 
 你好 &amp;amp;amp;nbsp; 可否帮我看下
 我知道直接放项目依赖就可以，我就是想先再源码里改成我想要的再添加依赖再改对应的地方就可以
 我这边把我改了的源码发你看下，你原本的一屏展示3个，左右各露出一点，点击事件和滑动事件都正常，但我这边是需要一屏能展示5个（好像到时加依赖时没找到怎么设置这个方法mViewPager.setOffscreenPageLimit(5);），所以修改了我前面说得两个地方和布局里clipChildrenLeftRightMargin属性，可能就出问题了，是不是和你很多地方比较一屏是否大于3个有关系 麻烦帮我看下 谢谢
 
 
 
 
 
 ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------
 发件人:&amp;amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;amp;gt;;
 发送时间:&amp;amp;amp;nbsp;2020年4月21日(星期二) 下午5:03
 收件人:&amp;amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;amp;gt;;
 抄送:&amp;amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;
 主题:&amp;amp;amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)
 
 
 
 
 
 代码版本号，其实不用下载源码的
 
 
 
 
 | |
 萧海斌
 邮箱：xhb_199409@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月21日 16:59，chenjy 写道：
 
 你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
 我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
 不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 
 从QQ邮箱发来的超大附件
 
 XBanner-master.rar (24.57M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7331383133dd14ce05de66924434501f0c07085557005007195301085b195602065515090605531d0c0359055605505557090e50622662687650565f07464f5d55424c54101a1051463105&amp;amp;amp;t=exs_ftn_download&amp;amp;amp;code=4181b4b0

**Comment by xiaohaibin** [comment]
这样设置确实有问题，我修复下




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 18:55，chenjy 写道：

130


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.XIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上6:25
收件人:&nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&gt;;
抄送:&nbsp;"2740907825"<2740907825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





margin你改成多少了




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 18:22，chenjy 写道：

demo是没问题的&amp;nbsp; 我改了这个clipChildrenLeftRightMargin和这个mViewPager.setOffscreenPageLimit(5)就有问题了





------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年4月21日(星期二) 晚上6:12
收件人:&amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"2740907825"<2740907825@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





你跑下demo试下




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 17:51，chenjy 写道：

对的，昨天下的。应该就是和我设置clipChildrenLeftRightMargin这个的原因


------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
发件人:&amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;gt;;
发送时间:&amp;amp;nbsp;2020年4月21日(星期二) 下午5:50
收件人:&amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;gt;;
抄送:&amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;
主题:&amp;amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





是拉的最新的版本源码么




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 17:21，chenjy 写道：

你好 &amp;amp;amp;nbsp; 可否帮我看下
我知道直接放项目依赖就可以，我就是想先再源码里改成我想要的再添加依赖再改对应的地方就可以
我这边把我改了的源码发你看下，你原本的一屏展示3个，左右各露出一点，点击事件和滑动事件都正常，但我这边是需要一屏能展示5个（好像到时加依赖时没找到怎么设置这个方法mViewPager.setOffscreenPageLimit(5);），所以修改了我前面说得两个地方和布局里clipChildrenLeftRightMargin属性，可能就出问题了，是不是和你很多地方比较一屏是否大于3个有关系 麻烦帮我看下 谢谢





------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------
发件人:&amp;amp;amp;nbsp;"Mr.XIAO"<notifications@github.com&amp;amp;amp;gt;;
发送时间:&amp;amp;amp;nbsp;2020年4月21日(星期二) 下午5:03
收件人:&amp;amp;amp;nbsp;"xiaohaibin/XBanner"<XBanner@noreply.github.com&amp;amp;amp;gt;;
抄送:&amp;amp;amp;nbsp;"2740907825"<2740907825@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;
主题:&amp;amp;amp;nbsp;Re: [xiaohaibin/XBanner] 一屏显示多个时banner的item点击事件对应的position不对 (#163)





代码版本号，其实不用下载源码的




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 16:59，chenjy 写道：

你说得版本是指你代码的还是啥，我就直接拿你项目代码down下来然后直接先修改成自己想要的再移到自己项目里
我这边只改了两处，一是item布局layout_fresco_imageview里设置了固定宽高 二是添加了缓存页面为5 mViewPager.setOffscreenPageLimit(5);
不添加这个默认进来只看得到2张，需要往右滑拿到下一张才显示出

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

XBanner-master.rar (24.57M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7331383133dd14ce05de66924434501f0c07085557005007195301085b195602065515090605531d0c0359055605505557090e50622662687650565f07464f5d55424c54101a1051463105&amp;amp;amp;t=exs_ftn_download&amp;amp;amp;code=4181b4b0

**Comment by AliceChjy** [comment]
好的  麻烦啦

**Comment by AliceChjy** [comment]
大神，我这边直接发邮件咨询了几个问题，不知道能不能看到

**Comment by xiaohaibin** [comment]
已修复，请更新最新版本
