### ISSUE TITLE
当只有两张图片时候，显示空白页

### ISSUE THREAD

**Issue by oreo** [xiaohaibin/XBanner#88]
左滑会先出现空白页 然后才会显示真实图片，大概1秒左右。右滑却正常

**Comment by oreo** [comment]
![image](https://user-images.githubusercontent.com/13199432/54595762-3f473500-4a6e-11e9-8bae-bf6d452252f2.png)
以上是我布局中的配置

**Comment by oreo** [comment]
我的业务是不需要自动轮播的，我暂时的解决方案是开启自动轮播，自动轮播的时间设置为300000，然后拿到数据后在通过代码设置为不自动轮播， 这样左滑右滑都正常

**Comment by oreo** [comment]
<com.stx.xhb.xbanner.XBanner
                        app:isHandLoop="true"
                        app:isShowIndicatorOnlyOne="false"
                        app:isShowTips="false"
                        app:AutoPlayTime="300000"
                        app:pageChangeDuration="800"
                        app:pointsContainerBackground="@drawable/app_dot_bg_gradient"
                        app:pointNormal="@drawable/app_dot_white"
                        app:pointSelect="@drawable/app_dot_yellow"
                        app:pointLeftRightPadding="5pt"
                        app:layout_constraintTop_toTopOf="parent"
                        app:layout_constraintRight_toRightOf="parent"
                        app:layout_constraintLeft_toLeftOf="parent"
                        android:id="@+id/banner"
                        android:layout_width="0pt"
                        app:layout_constraintDimensionRatio="h,375:210"
                        android:layout_height="0pt"/>

我这样设置就正常， 我是在fragment中使用的

**Comment by xiaohaibin** [comment]
版本号多少




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年03月19日 17:45，oreo 写道：

<com.stx.xhb.xbanner.XBanner
app:isHandLoop="true"
app:isShowIndicatorOnlyOne="false"
app:isShowTips="false"
app:AutoPlayTime="300000"
app:pageChangeDuration="800"
app:pointsContainerBackground="@drawable/app_dot_bg_gradient"
app:pointNormal="@drawable/app_dot_white"
app:pointSelect="@drawable/app_dot_yellow"
app:pointLeftRightPadding="5pt"
app:layout_constraintTop_toTopOf="parent"
app:layout_constraintRight_toRightOf="parent"
app:layout_constraintLeft_toLeftOf="parent"
android:id="@+id/banner"
android:layout_width="0pt"
app:layout_constraintDimensionRatio="h,375:210"
android:layout_height="0pt"/>

我这样设置就正常， 我是在fragment中使用的

**Comment by oreo** [comment]
> 版本号多少 | | 萧海斌 邮箱：xhb_199409@163.com | 签名由 网易邮箱大师 定制 在2019年03月19日 17:45，oreo 写道： <com.stx.xhb.xbanner.XBanner app:isHandLoop="true" app:isShowIndicatorOnlyOne="false" app:isShowTips="false" app:AutoPlayTime="300000" app:pageChangeDuration="800" app:pointsContainerBackground="@drawable/app_dot_bg_gradient" app:pointNormal="@drawable/app_dot_white" app:pointSelect="@drawable/app_dot_yellow" app:pointLeftRightPadding="5pt" app:layout_constraintTop_toTopOf="parent" app:layout_constraintRight_toRightOf="parent" app:layout_constraintLeft_toLeftOf="parent" android:id="@+id/banner" android:layout_width="0pt" app:layout_constraintDimensionRatio="h,375:210" android:layout_height="0pt"/> 我这样设置就正常， 我是在fragment中使用的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

版本是1.6.4

**Comment by xiaohaibin** [comment]
我回去看看




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年03月19日 17:47，oreo 写道：

版本号多少 | | 萧海斌 邮箱：xhb_199409@163.com | 签名由 网易邮箱大师 定制 在2019年03月19日 17:45，oreo 写道： <com.stx.xhb.xbanner.XBanner app:isHandLoop="true" app:isShowIndicatorOnlyOne="false" app:isShowTips="false" app:AutoPlayTime="300000" app:pageChangeDuration="800" app:pointsContainerBackground="@drawable/app_dot_bg_gradient" app:pointNormal="@drawable/app_dot_white" app:pointSelect="@drawable/app_dot_yellow" app:pointLeftRightPadding="5pt" app:layout_constraintTop_toTopOf="parent" app:layout_constraintRight_toRightOf="parent" app:layout_constraintLeft_toLeftOf="parent" android:id="@+id/banner" android:layout_width="0pt" app:layout_constraintDimensionRatio="h,375:210" android:layout_height="0pt"/> 我这样设置就正常， 我是在fragment中使用的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

版本是1.6.4

**Comment by wangjianfengw** [comment]
我也遇到了这个问题  求解决

**Comment by xiaohaibin** [comment]
可否截个屏看看

**Comment by wangjianfengw** [comment]
![image](https://user-images.githubusercontent.com/20201762/55527391-67b86b80-56cb-11e9-8501-47ce2bbd68d3.png)
只有两张图  且xml中关闭自动滑动    向右滑动无问题   像左滑动会出现短暂空白   大神可否加QQ联系

**Comment by xiaohaibin** [comment]
846035385

**Comment by wangjianfengw** [comment]
加了  也加群了 都没人同意╭(╯^╰)╮

**Comment by xiaohaibin** [comment]
已修复 请更新版本至1.6.5
